name: deploy-production
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Setup
        run: sudo apt-get install httpie

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Deploy
        id: deploy
        uses: Pendect/action-rsyncer@v1.1.0
        env:
          DEPLOY_KEY: ${{secrets.DEPLOY_KEY}}
        with:
          flags: '-avzr --delete'
          options: ''
          ssh_options: ''
          src: './'
          dest: 'deploy@noproxy.iwgb.org.uk:/var/repo/iwgb-org-uk'

      - name: Status
        run: echo "${{ steps.deploy.outputs.status }}"

      - name: Build
        uses: appleboy/ssh-action@v0.0.7
        with:
          host: "noproxy.iwgb.org.uk"
          username: deploy
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd /var/repo/iwgb-org-uk/.deploy
            sh ./production.sh

      - name: Purge
        uses: jakejarvis/cloudflare-purge-action@0.3.0
        env:
          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}

      - name: Verify
        run: echo ::set-env name=status::$(http -h https://iwgb.org.uk | grep HTTP/ | cut -d ' ' -f 2)

      - name: Check
        if: env.status == 500
        run: exit 1

      - name: Notify
        run: http POST https://maker.ifttt.com/trigger/build/with/key/${{ secrets.IFTTT_KEY }} value1="${{ github.workflow }}" value2="${{ github.repository }}" value3="${{ github.run_id }}" --ignore-stdin





