name: deploy-production
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Setup
        run: sudo apt-get update && sudo apt-get install httpie

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Deploy
        id: deploy
        uses: Pendect/action-rsyncer@v1.1.0
        env:
          DEPLOY_KEY: ${{secrets.DEPLOY_KEY}}
        with:
          flags: -avzr --delete
          options: ''
          ssh_options: ''
          src: './'
          dest: ${{ secrets.DEPLOY_USER }}@noproxy.iwgb.org.uk:/var/repo/iwgb-org-uk

      - name: Build
        uses: appleboy/ssh-action@v0.0.7
        with:
          host: noproxy.iwgb.org.uk
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd /var/repo/iwgb-org-uk/.deploy
            sh ./production.sh

      - name: Purge cache
        uses: jakejarvis/cloudflare-purge-action@v0.3.0
        env:
          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}

      - name: Purge assets
        run: 'http GET https://api.keycdn.com/zones/purge/${{ secrets.KEYCDN_ZONE_ID }}.json -a ${{ secrets.KEYCDN_API_KEY}}:'

      - name: Verify
        run: echo ::set-env name=status::$(http -h https://iwgb.org.uk | grep HTTP/ | cut -d ' ' -f 2)
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

      - name: Check
        if: env.status == 500
        run: http POST https://maker.ifttt.com/trigger/build_failed/with/key/${{ secrets.IFTTT_KEY }} value1="${{ github.workflow }}" value2="${{ github.repository }}" --ignore-stdin && exit 1

      - name: Validate
        if: env.status != 500
        run: http POST https://maker.ifttt.com/trigger/build_success/with/key/${{ secrets.IFTTT_KEY }} value1="${{ github.workflow }}" value2="${{ github.repository }}" --ignore-stdin
