name: deploy-qa
on:
  push:
    branches:
      - develop

jobs:
  deploy:
    name: Deploy QA
    runs-on: ubuntu-latest

    steps:
      - name: Setup
        run: sudo apt-get install httpie

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: develop

      - name: Deploy
        id: deploy
        uses: Pendect/action-rsyncer@v1.1.0
        env:
          DEPLOY_KEY: ${{secrets.DEPLOY_KEY}}
        with:
          flags: '-avzr --delete'
          options: ''
          ssh_options: ''
          src: './'
          dest: 'deploy@noproxy.iwgb.org.uk:/var/repo/iwgb-org-uk-qa'

      - name: Status
        run: echo "${{ steps.deploy.outputs.status }}"

      - name: Build
        uses: appleboy/ssh-action@v0.0.2
        with:
          host: noproxy.iwgb.org.uk
          username: deploy
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd /var/repo/iwgb-org-uk-qa/.deploy
            sh ./qa.sh

      - name: Verify
        run: echo ::set-env name=status::$(http -a iwgb:${{ secrets.QA_PASSWORD }} -h https://qa.iwgb.org.uk | grep HTTP/ | cut -d ' ' -f 2)

      - name: Check
        if: env.status != 200
        run: exit 1

      - name: Notify
        run: http POST https://maker.ifttt.com/trigger/build/with/key/${{ secrets.IFTTT_KEY }} value1=${{ github.action }} value2=${{ github.repository }} value3=${{ github.run_id }}